[package]
name = "glaze"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "glaze"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.1"
serde_json = "1.0.86"

[dev-dependencies]
marine-rs-sdk-test = "0.9.1"
