[[module]]
name = "local_storage"
load_from = "/Users/bebo/localdev/examples/marine-examples/url-downloader/target/wasm32-wasi/release/local_storage.wasm"
logger_enabled = true

[module.wasi.mapped_dirs]
sites = "./tmp"

[[module]]
name = "curl_adapter"
load_from = "/Users/bebo/localdev/examples/marine-examples/url-downloader/target/wasm32-wasi/release/curl_adapter.wasm"
logger_enabled = true

  [module.mounted_binaries]
  curl = "/usr/bin/curl"

[[module]]
name = "url_downloader"
load_from = "/Users/bebo/localdev/examples/marine-examples/url-downloader/target/wasm32-wasi/release/url_downloader.wasm"
logger_enabled = true
