[package]
name = "echo-service"
version = "0.1.0"
authors = ["Fluence Team"]
edition = "2018"


[[bin]]
name = "echo_service"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version="0.10.1", feature=["log"]}
log = "0.4.14"

