[package]
name = "secure-greeter"
version = "0.1.0"
authors = ["The Fluence Team"]
edition = "2018"

[[bin]]
name = "secure_greeter"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version="0.6.10", feature=["log"]}
log = "0.4.14"
