modules_dir = "artifacts/"

[[module]]
    name = "curl_adapter"
    logger_enabled = true

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "ether_price_getter"
    logger_enabled = true
