modules_dir = "artifacts"


[[module]]
name = "curl_adapter"
mem_pages_count = 100
logger_enabled = true

[module.mounted_binaries]
curl = "/usr/bin/curl"


[[module]]
name = "ceramic_adapter"
mem_pages_count = 50
logger_enabled = true

[module.mounted_binaries]
ceramic = "/Users/bebo/.nvm/versions/node/v14.16.0/bin/ceramic"
