[package]
name = "curl-adapter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
path = "src/main.rs"
name = "curl-adapter"

[dependencies]
marine-rs-sdk = "0.8.0"
log = "0.4.8"
