modules_dir = "artifacts"

[[module]]
name = "curl_adapter"
max_heap_size = "100 KiB"
logger_enabled = true
[module.mounted_binaries]
curl = "/usr/bin/curl"

[[module]]
name = "near_rpc_services"
max_heap_size = "10 KiB"
logger_enabled = true
