modules_dir = "artifacts"

[[module]]
name = "curl_adapter"
mem_pages_count = 10
logger_enabled = true
[module.mounted_binaries]
curl = "/usr/bin/curl"

[[module]]
name = "near_rpc_services"
mem_pages_count = 10
logger_enabled = true
