[package]
name = "curl_adapter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
path = "src/main.rs"
name = "curl_adapter"

[dependencies]
marine-rs-sdk = "0.6.14"
log = "0.4.8"
