[package]
name = "local_storage"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "local_storage"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.9.0"
log = "0.4.8"

[dev-dependencies]
marine-rs-sdk-test = "0.10.2"
