[package]
name = "local_storage"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "local_storage"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.6.10", features = ["logger"] }
wasm-tracing-allocator = "0.1.1"
log = "0.4.8"
