[package]
name = "wasm-sqlite-test"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "sqlite_test"
path = "src/main.rs"

[dependencies]
fluence = "=0.4.2"
fce-sqlite-connector = "=0.2.0"
