[package]
name = "record-facade"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "records_facade"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.8.1"
test-record = { path = "../test-record" }
