[package]
name = "quickstart-5-timestamp-oracle"
version = "0.1.0"
authors = ["boneyard93501 <4523011+boneyard93501@users.noreply.github.com>"]
edition = "2018"
description = "ts-cons, a Marine wasi module"
license = "Apache-2.0"

[[bin]]
name = "ts_oracle"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.8.1", features = ["logger"] }
log = "0.4.14"
# picorand = "0.1.1"
nanorand = { version = "0.7.0", default-features = false, features = [
    "wyrand",
] }

[dev-dependencies]
marine-rs-sdk-test = "0.10.2"

[dev]
[profile.release]
opt-level = "s"
