modules_dir = "artifacts/"

[[module]]
    name = "curl_adapter"
    logger_enabled = false
    mem_pages_count = 1

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "price_getter_service"
    logger_enabled = false
    mem_pages_count = 1

[[module]]
    name = "mean_service"
    logger_enabled = false
    mem_pages_count = 1