[package]
name = "ipfs-adapter"
version = "0.1.5"
authors = ["boneyard93501 <4523011+boneyard93501@users.noreply.github.com>"]
edition = "2018"
description = "ipfs-adapter, a Marine wasi module"
license = "Apache-2.0"

[[bin]]
name = "ipfs_adapter"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.7.1", features = ["logger"] }
log = "0.4.14"

[dev-dependencies]
marine-rs-sdk-test = "0.8.2"

[dev]
[profile.release]
opt-level = "s"
