name: ci

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "!**.md"

concurrency:
  group: "gitops-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  js:
    name: "JS projects"
    uses: ./.github/workflows/js-projects.yml
