[package]
name = "wasm-greeting"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "The greeting module for the Fluence network"
repository = "https://github.com/fluencelabs/fce/tree/master/examples/greeting"
edition = "2018"
publish = false

[[bin]]
name = "greeting"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version="0.6.10", feature=["log"]}


